// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/s4heid/goom/cmd"
	"github.com/s4heid/goom/config"
)

type FakeManager struct {
	ReadConfigStub        func() (config.Config, error)
	readConfigMutex       sync.RWMutex
	readConfigArgsForCall []struct {
	}
	readConfigReturns struct {
		result1 config.Config
		result2 error
	}
	readConfigReturnsOnCall map[int]struct {
		result1 config.Config
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) ReadConfig() (config.Config, error) {
	fake.readConfigMutex.Lock()
	ret, specificReturn := fake.readConfigReturnsOnCall[len(fake.readConfigArgsForCall)]
	fake.readConfigArgsForCall = append(fake.readConfigArgsForCall, struct {
	}{})
	fake.recordInvocation("ReadConfig", []interface{}{})
	fake.readConfigMutex.Unlock()
	if fake.ReadConfigStub != nil {
		return fake.ReadConfigStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.readConfigReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeManager) ReadConfigCallCount() int {
	fake.readConfigMutex.RLock()
	defer fake.readConfigMutex.RUnlock()
	return len(fake.readConfigArgsForCall)
}

func (fake *FakeManager) ReadConfigCalls(stub func() (config.Config, error)) {
	fake.readConfigMutex.Lock()
	defer fake.readConfigMutex.Unlock()
	fake.ReadConfigStub = stub
}

func (fake *FakeManager) ReadConfigReturns(result1 config.Config, result2 error) {
	fake.readConfigMutex.Lock()
	defer fake.readConfigMutex.Unlock()
	fake.ReadConfigStub = nil
	fake.readConfigReturns = struct {
		result1 config.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) ReadConfigReturnsOnCall(i int, result1 config.Config, result2 error) {
	fake.readConfigMutex.Lock()
	defer fake.readConfigMutex.Unlock()
	fake.ReadConfigStub = nil
	if fake.readConfigReturnsOnCall == nil {
		fake.readConfigReturnsOnCall = make(map[int]struct {
			result1 config.Config
			result2 error
		})
	}
	fake.readConfigReturnsOnCall[i] = struct {
		result1 config.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readConfigMutex.RLock()
	defer fake.readConfigMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.Manager = new(FakeManager)
